id: A0958D8BA
title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
type: translation
pechas:
- I9F55C141
- I2BB92F8E
- I720799E0
- IB98BC217
- I7820AD1F
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:39:57.368984
  last_modified_at: 2023-01-04 11:39:57.368992
  collections:
  - Do Khyentse Yeshe Dorje Series
  - Works of Tibetan Masters
alignment_to_base:
  I9F55C141/7989: 6D95
  I2BB92F8E/C99B: 6D95
  I720799E0/B41B: 6D95
  IB98BC217/565B: 6D95
  I7820AD1F/EF36: 6D95
